
package orderdetail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderdetailSrv", targetNamespace = "http://Webservice.helman.com/", wsdlLocation = "http://localhost:8080/order/soap/orderdetail?wsdl")
public class OrderdetailSrv
    extends Service
{

    private final static URL ORDERDETAILSRV_WSDL_LOCATION;
    private final static WebServiceException ORDERDETAILSRV_EXCEPTION;
    private final static QName ORDERDETAILSRV_QNAME = new QName("http://Webservice.helman.com/", "OrderdetailSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/order/soap/orderdetail?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERDETAILSRV_WSDL_LOCATION = url;
        ORDERDETAILSRV_EXCEPTION = e;
    }

    public OrderdetailSrv() {
        super(__getWsdlLocation(), ORDERDETAILSRV_QNAME);
    }

    public OrderdetailSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERDETAILSRV_QNAME, features);
    }

    public OrderdetailSrv(URL wsdlLocation) {
        super(wsdlLocation, ORDERDETAILSRV_QNAME);
    }

    public OrderdetailSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERDETAILSRV_QNAME, features);
    }

    public OrderdetailSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderdetailSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderdetaitInt
     */
    @WebEndpoint(name = "OrderdetaitIntPort")
    public OrderdetaitInt getOrderdetaitIntPort() {
        return super.getPort(new QName("http://Webservice.helman.com/", "OrderdetaitIntPort"), OrderdetaitInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderdetaitInt
     */
    @WebEndpoint(name = "OrderdetaitIntPort")
    public OrderdetaitInt getOrderdetaitIntPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webservice.helman.com/", "OrderdetaitIntPort"), OrderdetaitInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERDETAILSRV_EXCEPTION!= null) {
            throw ORDERDETAILSRV_EXCEPTION;
        }
        return ORDERDETAILSRV_WSDL_LOCATION;
    }

}
