
package employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeInt", targetNamespace = "http://Webservice.helman.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeInt {


    /**
     * 
     * @param employeeNumber
     * @return
     *     returns employee.Employee
     */
    @WebMethod
    @WebResult(name = "Employee", partName = "Employee")
    @Action(input = "http://Webservice.helman.com/EmployeeInt/findbyidRequest", output = "http://Webservice.helman.com/EmployeeInt/findbyidResponse")
    public Employee findbyid(
        @WebParam(name = "employeeNumber", partName = "employeeNumber")
        long employeeNumber);

    /**
     * 
     * @return
     *     returns employee.EmployeeArray
     */
    @WebMethod
    @WebResult(name = "Employees", partName = "Employees")
    @Action(input = "http://Webservice.helman.com/EmployeeInt/findallRequest", output = "http://Webservice.helman.com/EmployeeInt/findallResponse")
    public EmployeeArray findall();

    /**
     * 
     * @param employee
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/EmployeeInt/updateRequest", output = "http://Webservice.helman.com/EmployeeInt/updateResponse")
    public long update(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

    /**
     * 
     * @param employeeNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/EmployeeInt/deleteRequest", output = "http://Webservice.helman.com/EmployeeInt/deleteResponse")
    public String delete(
        @WebParam(name = "employeeNumber", partName = "employeeNumber")
        long employeeNumber);

    /**
     * 
     * @param employee
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/EmployeeInt/insertRequest", output = "http://Webservice.helman.com/EmployeeInt/insertResponse")
    public long insert(
        @WebParam(name = "Employee", partName = "Employee")
        Employee employee);

}
