
package product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductInt", targetNamespace = "http://Webservice.helman.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductInt {


    /**
     * 
     * @return
     *     returns product.ProductArray
     */
    @WebMethod
    @WebResult(name = "products", partName = "products")
    @Action(input = "http://Webservice.helman.com/ProductInt/findallRequest", output = "http://Webservice.helman.com/ProductInt/findallResponse")
    public ProductArray findall();

    /**
     * 
     * @param productCode
     * @return
     *     returns product.Product
     */
    @WebMethod
    @WebResult(name = "product", partName = "product")
    @Action(input = "http://Webservice.helman.com/ProductInt/findbyidRequest", output = "http://Webservice.helman.com/ProductInt/findbyidResponse")
    public Product findbyid(
        @WebParam(name = "productCode", partName = "productCode")
        String productCode);

    /**
     * 
     * @param product
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/ProductInt/updateRequest", output = "http://Webservice.helman.com/ProductInt/updateResponse")
    public String update(
        @WebParam(name = "Product", partName = "Product")
        Product product);

    /**
     * 
     * @param productCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/ProductInt/deleteRequest", output = "http://Webservice.helman.com/ProductInt/deleteResponse")
    public String delete(
        @WebParam(name = "productCode", partName = "productCode")
        String productCode);

    /**
     * 
     * @param product
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/ProductInt/insertRequest", output = "http://Webservice.helman.com/ProductInt/insertResponse")
    public String insert(
        @WebParam(name = "Product", partName = "Product")
        Product product);

}
