
package product;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductSrv", targetNamespace = "http://Webservice.helman.com/", wsdlLocation = "http://localhost:8080/order/soap/product?wsdl")
public class ProductSrv
    extends Service
{

    private final static URL PRODUCTSRV_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSRV_EXCEPTION;
    private final static QName PRODUCTSRV_QNAME = new QName("http://Webservice.helman.com/", "ProductSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/order/soap/product?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSRV_WSDL_LOCATION = url;
        PRODUCTSRV_EXCEPTION = e;
    }

    public ProductSrv() {
        super(__getWsdlLocation(), PRODUCTSRV_QNAME);
    }

    public ProductSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSRV_QNAME, features);
    }

    public ProductSrv(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSRV_QNAME);
    }

    public ProductSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSRV_QNAME, features);
    }

    public ProductSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductInt
     */
    @WebEndpoint(name = "ProductIntPort")
    public ProductInt getProductIntPort() {
        return super.getPort(new QName("http://Webservice.helman.com/", "ProductIntPort"), ProductInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductInt
     */
    @WebEndpoint(name = "ProductIntPort")
    public ProductInt getProductIntPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webservice.helman.com/", "ProductIntPort"), ProductInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSRV_EXCEPTION!= null) {
            throw PRODUCTSRV_EXCEPTION;
        }
        return PRODUCTSRV_WSDL_LOCATION;
    }

}
