
package office;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OfficeSrv", targetNamespace = "http://Webservice.helman.com/", wsdlLocation = "http://localhost:8080/order/soap/office?wsdl")
public class OfficeSrv
    extends Service
{

    private final static URL OFFICESRV_WSDL_LOCATION;
    private final static WebServiceException OFFICESRV_EXCEPTION;
    private final static QName OFFICESRV_QNAME = new QName("http://Webservice.helman.com/", "OfficeSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/order/soap/office?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OFFICESRV_WSDL_LOCATION = url;
        OFFICESRV_EXCEPTION = e;
    }

    public OfficeSrv() {
        super(__getWsdlLocation(), OFFICESRV_QNAME);
    }

    public OfficeSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), OFFICESRV_QNAME, features);
    }

    public OfficeSrv(URL wsdlLocation) {
        super(wsdlLocation, OFFICESRV_QNAME);
    }

    public OfficeSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OFFICESRV_QNAME, features);
    }

    public OfficeSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OfficeSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OfficeInt
     */
    @WebEndpoint(name = "OfficeIntPort")
    public OfficeInt getOfficeIntPort() {
        return super.getPort(new QName("http://Webservice.helman.com/", "OfficeIntPort"), OfficeInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OfficeInt
     */
    @WebEndpoint(name = "OfficeIntPort")
    public OfficeInt getOfficeIntPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webservice.helman.com/", "OfficeIntPort"), OfficeInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OFFICESRV_EXCEPTION!= null) {
            throw OFFICESRV_EXCEPTION;
        }
        return OFFICESRV_WSDL_LOCATION;
    }

}
