
package payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentInt", targetNamespace = "http://Webservice.helman.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentInt {


    /**
     * 
     * @return
     *     returns payment.PaymentArray
     */
    @WebMethod
    @WebResult(name = "payments", partName = "payments")
    @Action(input = "http://Webservice.helman.com/PaymentInt/findallRequest", output = "http://Webservice.helman.com/PaymentInt/findallResponse")
    public PaymentArray findall();

    /**
     * 
     * @param checkNumber
     * @param customerNumber
     * @return
     *     returns payment.Payment
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Webservice.helman.com/PaymentInt/findbyidRequest", output = "http://Webservice.helman.com/PaymentInt/findbyidResponse")
    public Payment findbyid(
        @WebParam(name = "customerNumber", partName = "customerNumber")
        int customerNumber,
        @WebParam(name = "checkNumber", partName = "checkNumber")
        String checkNumber);

    /**
     * 
     * @param payment
     * @return
     *     returns payment.PaymentPK
     */
    @WebMethod
    @WebResult(name = "PaymentPK", partName = "PaymentPK")
    @Action(input = "http://Webservice.helman.com/PaymentInt/updateRequest", output = "http://Webservice.helman.com/PaymentInt/updateResponse")
    public PaymentPK update(
        @WebParam(name = "Payment", partName = "Payment")
        Payment payment);

    /**
     * 
     * @param checkNumber
     * @param customerNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/PaymentInt/deleteRequest", output = "http://Webservice.helman.com/PaymentInt/deleteResponse")
    public String delete(
        @WebParam(name = "customerNumber", partName = "customerNumber")
        int customerNumber,
        @WebParam(name = "checkNumber", partName = "checkNumber")
        String checkNumber);

    /**
     * 
     * @param payment
     * @return
     *     returns payment.PaymentPK
     */
    @WebMethod
    @WebResult(name = "PaymentPK", partName = "PaymentPK")
    @Action(input = "http://Webservice.helman.com/PaymentInt/insertRequest", output = "http://Webservice.helman.com/PaymentInt/insertResponse")
    public PaymentPK insert(
        @WebParam(name = "Payment", partName = "Payment")
        Payment payment);

}
