
package payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentSrv", targetNamespace = "http://Webservice.helman.com/", wsdlLocation = "http://localhost:8080/order/soap/payment?wsdl")
public class PaymentSrv
    extends Service
{

    private final static URL PAYMENTSRV_WSDL_LOCATION;
    private final static WebServiceException PAYMENTSRV_EXCEPTION;
    private final static QName PAYMENTSRV_QNAME = new QName("http://Webservice.helman.com/", "PaymentSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/order/soap/payment?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTSRV_WSDL_LOCATION = url;
        PAYMENTSRV_EXCEPTION = e;
    }

    public PaymentSrv() {
        super(__getWsdlLocation(), PAYMENTSRV_QNAME);
    }

    public PaymentSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTSRV_QNAME, features);
    }

    public PaymentSrv(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTSRV_QNAME);
    }

    public PaymentSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTSRV_QNAME, features);
    }

    public PaymentSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentInt
     */
    @WebEndpoint(name = "PaymentIntPort")
    public PaymentInt getPaymentIntPort() {
        return super.getPort(new QName("http://Webservice.helman.com/", "PaymentIntPort"), PaymentInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentInt
     */
    @WebEndpoint(name = "PaymentIntPort")
    public PaymentInt getPaymentIntPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webservice.helman.com/", "PaymentIntPort"), PaymentInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTSRV_EXCEPTION!= null) {
            throw PAYMENTSRV_EXCEPTION;
        }
        return PAYMENTSRV_WSDL_LOCATION;
    }

}
