
package customer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerInt", targetNamespace = "http://Webservice.helman.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerInt {


    /**
     * 
     * @param customerNumber
     * @return
     *     returns customer.Customer
     */
    @WebMethod
    @WebResult(name = "Customer", partName = "Customer")
    @Action(input = "http://Webservice.helman.com/CustomerInt/findByIdRequest", output = "http://Webservice.helman.com/CustomerInt/findByIdResponse")
    public Customer findById(
        @WebParam(name = "customerNumber", partName = "customerNumber")
        int customerNumber);

    /**
     * 
     * @return
     *     returns customer.CustomerArray
     */
    @WebMethod
    @WebResult(name = "Customers", partName = "Customers")
    @Action(input = "http://Webservice.helman.com/CustomerInt/findallRequest", output = "http://Webservice.helman.com/CustomerInt/findallResponse")
    public CustomerArray findall();

    /**
     * 
     * @param customer
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/CustomerInt/updateRequest", output = "http://Webservice.helman.com/CustomerInt/updateResponse")
    public String update(
        @WebParam(name = "customer", partName = "customer")
        Customer customer);

    /**
     * 
     * @param customerNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/CustomerInt/deleteRequest", output = "http://Webservice.helman.com/CustomerInt/deleteResponse")
    public String delete(
        @WebParam(name = "customerNumber", partName = "customerNumber")
        int customerNumber);

    /**
     * 
     * @param customer
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "ReturnStatus", partName = "ReturnStatus")
    @Action(input = "http://Webservice.helman.com/CustomerInt/insertRequest", output = "http://Webservice.helman.com/CustomerInt/insertResponse")
    public String insert(
        @WebParam(name = "customer", partName = "customer")
        Customer customer);

}
