
package order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderInt", targetNamespace = "http://Webservice.helman.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderInt {


    /**
     * 
     * @return
     *     returns order.OrderArray
     */
    @WebMethod
    @WebResult(name = "orders", partName = "orders")
    @Action(input = "http://Webservice.helman.com/OrderInt/findallRequest", output = "http://Webservice.helman.com/OrderInt/findallResponse")
    public OrderArray findall();

    /**
     * 
     * @param orderNumber
     * @return
     *     returns order.Order
     */
    @WebMethod
    @WebResult(name = "order", partName = "order")
    @Action(input = "http://Webservice.helman.com/OrderInt/findbyidRequest", output = "http://Webservice.helman.com/OrderInt/findbyidResponse")
    public Order findbyid(
        @WebParam(name = "orderNumber", partName = "orderNumber")
        int orderNumber);

    /**
     * 
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/OrderInt/updateRequest", output = "http://Webservice.helman.com/OrderInt/updateResponse")
    public String update(
        @WebParam(name = "Order", partName = "Order")
        Order order);

    /**
     * 
     * @param orderNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/OrderInt/deleteRequest", output = "http://Webservice.helman.com/OrderInt/deleteResponse")
    public String delete(
        @WebParam(name = "orderNumber", partName = "orderNumber")
        int orderNumber);

    /**
     * 
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "returnStatus", partName = "returnStatus")
    @Action(input = "http://Webservice.helman.com/OrderInt/insertRequest", output = "http://Webservice.helman.com/OrderInt/insertResponse")
    public String insert(
        @WebParam(name = "Order", partName = "Order")
        Order order);

}
