
package order;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderSrv", targetNamespace = "http://Webservice.helman.com/", wsdlLocation = "http://localhost:8080/order/soap/order?wsdl")
public class OrderSrv
    extends Service
{

    private final static URL ORDERSRV_WSDL_LOCATION;
    private final static WebServiceException ORDERSRV_EXCEPTION;
    private final static QName ORDERSRV_QNAME = new QName("http://Webservice.helman.com/", "OrderSrv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/order/soap/order?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSRV_WSDL_LOCATION = url;
        ORDERSRV_EXCEPTION = e;
    }

    public OrderSrv() {
        super(__getWsdlLocation(), ORDERSRV_QNAME);
    }

    public OrderSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSRV_QNAME, features);
    }

    public OrderSrv(URL wsdlLocation) {
        super(wsdlLocation, ORDERSRV_QNAME);
    }

    public OrderSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSRV_QNAME, features);
    }

    public OrderSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderInt
     */
    @WebEndpoint(name = "OrderIntPort")
    public OrderInt getOrderIntPort() {
        return super.getPort(new QName("http://Webservice.helman.com/", "OrderIntPort"), OrderInt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderInt
     */
    @WebEndpoint(name = "OrderIntPort")
    public OrderInt getOrderIntPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webservice.helman.com/", "OrderIntPort"), OrderInt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSRV_EXCEPTION!= null) {
            throw ORDERSRV_EXCEPTION;
        }
        return ORDERSRV_WSDL_LOCATION;
    }

}
